name = "SnowLinModPack-1.20.1"
author = "SnowLin"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a204b4c002f775df2cceb0dd57dd40203e87e9f54e54df9615d725ccd83dfc1b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4", "1.20"]
