name = "SnowLinModPack-1.20.1"
author = "SnowLin"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78ce6a785e12b30fd1c3596de2ff39f9cba277027923b3ec7b17d07daed7f990"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.19.4", "1.20"]
