name = "雪鈴模組包-1.19.4"
author = "雪鈴"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59e847a31f8f06587a535d4dc6612e9c9b00b1ad94dcf774f585d89022f202a9"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19"]
