name = "SnowLinModPack-1.19.4"
author = "SnowLin"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb267e1dc821213dae745afc925111c512a77ce5ed61e05cb792a838fcd8901c"

[versions]
fabric = "0.14.23"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19"]
