name = "雪鈴模組包-1.19.4"
author = "SnowLin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "326b53f560e0488958831c4eae204794f4940831439b9415b8c63ee1901cc654"

[versions]
fabric = "0.14.21"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19"]
